//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministracionEscuela.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inscripcion
    {
        public int InscripcionID { get; set; }
        public Nullable<decimal> Grado { get; set; }
        public int AlumnoID { get; set; }
        public int CursoID { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Curso Curso { get; set; }
    }
}
